/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ch.so.agi;

import java.util.ArrayList;

import org.graalvm.nativeimage.IsolateThread;
import org.graalvm.nativeimage.c.function.CEntryPoint;

import ch.interlis.ili2c.Ili2c;
import ch.interlis.ili2c.Ili2cException;
import ch.interlis.ili2c.config.Configuration;
import ch.interlis.ili2c.metamodel.TransferDescription;
import ch.interlis.ilirepository.IliManager;

//https://www.graalvm.org/sdk/javadoc/org/graalvm/nativeimage/c/function/CEntryPoint.html

public class Ili2cUtils {
    
    @CEntryPoint(name = "getLastModelName")
    public static char getLastModelName(IsolateThread thread, char foo) {
        IliManager manager = new IliManager();
        String repositories[] = new String[] {
                "http://models.interlis.ch/", 
                "http://models.kkgeo.ch/", 
                "http://models.geo.admin.ch/" 
        };
        
        manager.setRepositories(repositories);
        
        ArrayList<String> ilifiles = new ArrayList<String>();
        ilifiles.add(String.valueOf(foo));

        Configuration config;

        TransferDescription td = null;
        try {
            config = manager.getConfigWithFiles(ilifiles);
            td = Ili2c.runCompiler(config);
        } catch (Ili2cException e) {
            e.printStackTrace();
        }
                
        if (td == null) {
            // Bricht C-Programm ab. Muss anders gelöst werden.
            throw new IllegalArgumentException("INTERLIS compiler failed");
        }
        
        System.out.println(td.getLastModel().getName());
        
        return td.getLastModel().getName().charAt(0);
    }
}
